### PR TITLE
Added go module to specify dependencies.

### PR DESCRIPTION
**Pull request by BjoernSchilberg**
I added a go.mod and go.sum file to track your code's dependencies. This keeps builds reproducible and gives you direct control over which module versions to use.

### CODE REVIEW

**Comment by unklnik** [comment]
OK if you want fine with me

**Comment by unklnik** [comment]
Does it compile with Purego? I see you added it as  dependency, I have not actually tried compiling with Purego, only Cgo. So, what if people want to compile with Cgo, will that still be OK?

**Comment by celioreyes** [comment]
Should be fine as long as they enable it I believe. `CGO_ENABLED=1 go build ...`

**Comment by unklnik** [comment]
@celioreyes yes you are right, downloaded and builds fine

**Pull request merged**
